# Generated by Django 5.0.2 on 2024-02-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinery',
            name='maintenance_cost',
        ),
        migrations.RemoveField(
            model_name='machinery',
            name='maintenance_date',
        ),
        migrations.AddField(
            model_name='machinery',
            name='plate_number',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
