# Generated by Django 5.0.2 on 2024-02-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0002_remove_machinery_maintenance_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='tag_number',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
