# Generated by Django 3.2 on 2024-02-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0004_expenditure_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='user_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='user_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='user_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='user_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='user_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
