# Generated by Django 3.2 on 2024-02-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0005_auto_20240222_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='user_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='user_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='user_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='user_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='user_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
